#!/usr/bin/env bash

if [ "$SUPERVISOR_PHP_USER" != "root" ] && [ "$SUPERVISOR_PHP_USER" != "sail" ]; then
    echo "You should set SUPERVISOR_PHP_USER to either 'sail' or 'root'."
    exit 1
fi

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

# NginxとPHP-FPMをバックグラウンドで起動し、ログを標準出力にリダイレクト
/usr/sbin/php-fpm8.4 -F & # PHP-FPMをフォアグラウンドで起動し、バックグラウンドに送る
/usr/sbin/nginx -g "daemon off;" & # Nginxをフォアグラウンドで起動し、バックグラウンドに送る

# 両方のプロセスが終了するのを待つ
wait -n

# どちらかのプロセスがエラーで終了した場合、コンテナも終了する
exit $?
